# Generated by Django 4.2.4 on 2023-09-04 11:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="footballclub",
            fields=[
                ("name", models.CharField(max_length=30)),
                ("history", models.TextField(max_length=500, null=True)),
                ("estd", models.IntegerField(help_text="Year")),
                ("country", models.CharField(max_length=30)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
