# Generated by Django 4.2.4 on 2023-09-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footballfanapp", "0002_footballclub_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footballclub",
            name="history",
        ),
        migrations.AddField(
            model_name="footballclub",
            name="abb",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="footballclub",
            name="description",
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
