# Generated by Django 4.2.4 on 2023-09-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballfanapp', '0003_remove_footballclub_history_footballclub_abb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballclub',
            name='slogan',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
