# Generated by Django 4.2.4 on 2023-09-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballfanapp', '0004_footballclub_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballclub',
            name='league',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
