# Generated by Django 4.2.4 on 2023-09-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballfanapp', '0006_footballclub_official_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballclub',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
