# Generated by Django 4.2.4 on 2023-09-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballfanapp', '0007_footballclub_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballclub',
            name='created',
        ),
        migrations.AddField(
            model_name='footballclub',
            name='home_venue',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
