# Generated by Django 4.2.4 on 2023-09-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballfanapp', '0008_remove_footballclub_created_footballclub_home_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballclub',
            name='current_manager',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='footballclub',
            name='logo',
            field=models.ImageField(blank=True, default='default_manager_pic.png', null=True, upload_to=''),
        ),
    ]
