# Generated by Django 4.2.4 on 2023-09-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballfanapp', '0009_footballclub_current_manager_alter_footballclub_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballclub',
            name='manager_pic',
            field=models.ImageField(blank=True, default='default_manager_pic.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='footballclub',
            name='logo',
            field=models.ImageField(blank=True, default='default_logo.png', null=True, upload_to=''),
        ),
    ]
