# Generated by Django 4.2.4 on 2023-09-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballfanapp', '0010_footballclub_manager_pic_alter_footballclub_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballclub',
            name='logo',
            field=models.ImageField(blank=True, default='default_logo.png', null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='footballclub',
            name='manager_pic',
            field=models.ImageField(blank=True, default='default_manager_pic.png', null=True, upload_to='managers/'),
        ),
    ]
