# Generated by Django 4.2.4 on 2023-09-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballfanapp', '0011_alter_footballclub_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballclub',
            name='logo',
            field=models.ImageField(blank=True, default='default_logo.png', null=True, upload_to='club_logo/'),
        ),
    ]
