# Generated by Django 4.2.4 on 2023-09-20 14:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('footballfanapp', '0012_alter_footballclub_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='internationalteam',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('abb', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(max_length=5000, null=True)),
                ('logo', models.ImageField(blank=True, default='default_logo.png', null=True, upload_to='int_logo/')),
                ('official_site', models.CharField(max_length=200, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('current_manager', models.CharField(max_length=50, null=True)),
                ('manager_pic', models.ImageField(blank=True, default='default_manager_pic.png', null=True, upload_to='managers/')),
            ],
        ),
    ]
