# Generated by Django 4.2.4 on 2023-09-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballfanapp', '0013_internationalteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballclub',
            name='ucl_won',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='internationalteam',
            name='copa_won',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='internationalteam',
            name='euro_won',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='internationalteam',
            name='wc_won',
            field=models.IntegerField(null=True),
        ),
    ]
