# Generated by Django 4.2.4 on 2023-09-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballfanapp', '0014_footballclub_ucl_won_internationalteam_copa_won_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballclub',
            name='manager_pic',
            field=models.ImageField(blank=True, default='default_manager_pic.png', null=True, upload_to='club_managers/'),
        ),
        migrations.AlterField(
            model_name='footballclub',
            name='ucl_won',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='internationalteam',
            name='copa_won',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='internationalteam',
            name='euro_won',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='internationalteam',
            name='manager_pic',
            field=models.ImageField(blank=True, default='default_manager_pic.png', null=True, upload_to='int_managers/'),
        ),
        migrations.AlterField(
            model_name='internationalteam',
            name='wc_won',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
