# Generated by Django 4.2.4 on 2023-09-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballfanapp', '0015_alter_footballclub_manager_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalteam',
            name='flag',
            field=models.ImageField(blank=True, default='flag_default.png', null=True, upload_to='int_flag/'),
        ),
    ]
