# Generated by Django 4.2.4 on 2023-09-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballfanapp', '0016_internationalteam_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballclub',
            name='venue_pic',
            field=models.ImageField(blank=True, default='home_default.png', null=True, upload_to='club_home_venue/'),
        ),
    ]
