# Generated by Django 4.2.4 on 2023-09-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballfanapp', '0017_footballclub_venue_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalteam',
            name='continent',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
